Repository VulnerabilityHistoryProject/tomcat-vulnerabilities, pull requests merged in 2019-06, with the labels that each got.

#24 Update CVE-2017-15706.yml
  cves/CVE-2017-15706.yml
Labels: Cohort M

#25 CVE-2018-11784
  cves/CVE-2018-11784.yml
Labels: Cohort P

#23 CVE-2011-0013
  cves/CVE-2011-0013.yml
Labels: Cohort D

#22 khk8083 pull request for CVE-2017-12617
  cves/CVE-2017-12617.yml
Labels: Cohort M

#21 CVE-2010-3718
  cves/CVE-2010-3718.yml
Labels: Cohort C

#20 CVE-2011-2526
  cves/CVE-2011-2526.yml
Labels: Cohort F

#19 CVE-2009-2901
  cves/CVE-2009-2901.yml
Labels: Cohort A

#18 CVE-2018-8037.yml
  cves/CVE-2018-8037.yml
Labels: Cohort Q

#17 CVE-2011-1183
  cves/CVE-2011-1183.yml
Labels: Cohort D

#14 CVE-2011-1088
  cves/CVE-2011-1088.yml
Labels: Cohort D

#13 CVE-2014-0095
  cves/CVE-2014-0095.yml
Labels: Cohort J

#12 CVE-2013-2071
  cves/CVE-2013-2071.yml
Labels: Cohort I

#7 CVE-2011-3190
  cves/CVE-2011-3190.yml
Labels: Cohort G

#6 CVE-2017-7675
  cves/CVE-2017-7675.yml
Labels: Cohort O

#5 CVE-2018-1305
  cves/CVE-2018-1305.yml
Labels: Cohort P

#2 CVE-2011-3376
  cves/CVE-2011-3376.yml
Labels: Cohort G
