Repository VulnerabilityHistoryProject/tomcat-vulnerabilities, pull requests merged in 2020-02, with the labels that each got.

#53 CVE-2011-2729
  cves/CVE-2011-2729.yml
Labels: Cohort M

#52 CVE-2016-8747
  cves/CVE-2016-8747.yml
Labels: Cohort M

#51 CVE-2015-5351
  cves/CVE-2015-5351.yml
Labels: Cohort J

#50 CVE-2017-5648
  cves/CVE-2017-5648.yml
Labels: Cohort I

#49 CVE-2016-0763
  cves/CVE-2016-0763.yml
Labels: Cohort I

#48 CVE-2017-12615
  cves/CVE-2017-12615.yml
Labels: Cohort A

#47 CVE-2009-2902
  cves/CVE-2009-2902.yml
Labels: Cohort L

#46 CVE-2013-4444
  cves/CVE-2013-4444.yml
Labels: Cohort M

#45 CVE-2016-3092
  cves/CVE-2016-3092.yml
Labels: Cohort T

#44 CVE-2012-3439
  cves/CVE-2012-3439.yml
Labels: Cohort I

#43 CVE-2018-1336
  cves/CVE-2018-1336.yml
Labels: Cohort H

#42 CVE-2010-1157
  cves/CVE-2010-1157.yml
Labels: Cohort G

#41 CVE-2017-12616
  cves/CVE-2017-12616.yml
Labels: Cohort T

#32 CVE-2009-3555
  cves/CVE-2009-3555.yml
Labels: Cohort O

#40 CVE-2011-1184
  cves/CVE-2011-1184.yml
Labels: Cohort E

#38 CVE-2016-6817
  cves/CVE-2016-6817.yml
Labels: Cohort R

#36 CVE-2012-0022
  cves/CVE-2012-0022.yml
Labels: Cohort N

#35 Added CVE-2009-3548 Information
  cves/CVE-2009-3548.yml
Labels: Cohort S

#34 CVE-2017-5651
  cves/CVE-2017-5651.yml
Labels: Cohort J

#33 CVE-2011-2204
  cves/CVE-2011-2204.yml
Labels: Cohort O
